spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/store_reservation
    username: root
    password: seowon

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fortestseowon@gmail.com
    password: hwtjmijqnhpgluae
    properties.mail.smtp:
        timeout: 5000
        starttls.enable: true
        auth: true


logging:
  level:
    org:
      springframework:
        security: DEBUG


